name: Build container

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup environment
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Do stuff with docker
      - name: Run testing
        run: npm run test

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          repository: ${{ secrets.DOCKERHUB_PREVIEW_REPOSITORY }}
          cache-from: type=local,src=/tmp/.buildx-cache
          target: deploy
          tags: |
            type=sha

      # Clean up cache
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      
      # Trigger preview creation
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: create-preview.yml
          inputs: '{ "tag": ${{ github.sha }} }'
          repo: hackthe6ix-landing-2021
          owner: hack-the-6ix

