name: Create Preview

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specific container tag from preview container repository'
        required: true
      expire:
        description: 'When to kill the preview (Defaults to 1 week) (etc. yyyy-mm-dd)'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.event.inputs.tag }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Pull container (For checking)
        uses: docker/build-push-action@v2
        with:
          tags: hackthe6ix/${{ secrets.DOCKERHUB_PREVIEW_REPOSITORY }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          target: deploy
          pull: true
      

      # Setup expiry date
      - name: Get expiry date
        run: |
          if [ $EXPIRY_DATE ]; then OWO=$(date -d $EXPIRY_DATE) ; else OWO=$(date -d "+7 days") ; fi
          echo "EXPIRY_DATE=$OWO" >> $GITHUB_ENV
        env:
          EXPIRY_DATE: ${{ github.event.inputs.expire }}

      # Create build
      - name: Run generate preview script
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          script: /scripts/create-preview.sh -t ${{ github.event.inputs.tag }} -e ${{ github.event.inputs.expire }}
