name: Build production container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # We will now call build container with specific parameters
      - name: Get expiry date
        run: |
          echo "EXPIRY_DATE=$(date -d "+100 days")" >> $GITHUB_ENV

      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          workflow_file_name: build-container.yml
          inputs: '{ "tag": "${{ secrets.YEAR }}-latest", "subdomain": "${{ secrets.YEAR }}", "expire": "${{ env.EXPIRY_DATE }}", "dockerrepo": "${{ secrets.DOCKERHUB_REPOSITORY }}" }'
          repo: ${{ github.event.repository.name }}
          owner: hack-the-6ix
